### ISSUE TITLE
Data - apollo

### ISSUE THREAD

**Issue by linkygit** [Bustoslcar/Primer-trabajo-github#24]
Para concentrarse en tareas importantes y mantener los planes actualizados @--.  codigo  basico-

**Comment by linkygit** [comment]
Prueba terminada

**Comment by Bustoslcar** [comment]
Bien ... vamos de nuevo .... vamos a ver si nos organizamos y hacemos llamada por discord así lo hacemos juntos <3

**Comment by Bustoslcar** [comment]
Muy buen trabajo todos .
