### ISSUE TITLE
Se genero en rama Varela Daniel  el ejercicio numero 9 del código Python

### ISSUE THREAD

**Issue by linkygit** [Bustoslcar/Primer-trabajo-github#56]
print ("Consulta Historial de Servicios ")
max = int(input("Introduce cualquier caracter numerico para obtener el maximo gasto de consulta Toto: "))

historial5 = (8520, 9510, 7530, 3570, 1590)
def valorMaximo( historial5):

    mayor=historial5[0]

    for i in range(1,len(historial5)):
        if historial5[i]>mayor:
            mayor=historial5[i]

        return print("el valor maximo gastadoconsultas a Toto es de $ ", mayor)

valorMaximo( historial5)

**Comment by linkygit** [comment]
compila en https://edube.org/sandbox

**Comment by linkygit** [comment]
9) Crear una tupla en Python con el nombre de “Historial5” la cual contenga los siguientes valores:
          8520, 9510, 7530, 3570, 1590
Que representa montos de atención en pesos por diferentes servicios/consultas de la mascota “Toto”. Crear una
función para determinar el valor máximo de atención gastada en “Toto”.

**Comment by Bustoslcar** [comment]
FINALIZADO
